name: Bun Index Workflow

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run-index:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup cache for Bun
      uses: actions/cache@v3
      with:
        path: ~/.bun
        key: ${{ runner.os }}-bun-cache
        restore-keys: |
          ${{ runner.os }}-bun-cache

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Bun
      run: |
        npm install -g bun
        echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_OUTPUT
        echo "$BUN_INSTALL/bin" >> $GITHUB_PATH
        bun i

    - name: Run the news aggregator spider
      run: bun run index.ts
