name: Bun Index Workflow

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run-index:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Bun
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: bun

    - name: Install Bun
      run: |
        npm install -g bun
        echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_OUTPUT
        echo "$BUN_INSTALL/bin" >> $GITHUB_PATH

    - name: Run index.ts
      run: bun run index.ts
